services:
  api:
    image: node:18-alpine
    container_name: bolna-api
    restart: unless-stopped
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_TYPE=api
      # Add your API keys here or use a .env file
      # - OPENAI_API_KEY=your_openai_api_key
      # - DEEPGRAM_AUTH_TOKEN=your_deepgram_auth_token
      # - ELEVENLABS_API_KEY=your_elevenlabs_api_key
    volumes:
      - ./:/app
    command: >
      sh -c "npm install && 
             npm install -g @nestjs/cli && 
             npm run build && 
             node dist/main"
    depends_on:
      - redis
    networks:
      - bolna-network
      
  telephony:
    image: node:18-alpine
    container_name: bolna-telephony
    restart: unless-stopped
    working_dir: /app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=${TELEPHONY_PORT:-3001}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_TYPE=telephony
      # Add your telephony API keys here or use a .env file
      # - TWILIO_ACCOUNT_SID=your_twilio_account_sid
      # - TWILIO_AUTH_TOKEN=your_twilio_auth_token
      # - TWILIO_PHONE_NUMBER=your_twilio_phone_number
      # - PLIVO_AUTH_ID=your_plivo_auth_id
      # - PLIVO_AUTH_TOKEN=your_plivo_auth_token
      # - PLIVO_PHONE_NUMBER=your_plivo_phone_number
    volumes:
      - ./:/app
    command: >
      sh -c "npm install && 
             npm install -g @nestjs/cli && 
             npm run build && 
             node dist/telephony"
    depends_on:
      - redis
    networks:
      - bolna-network

  redis:
    image: redis:7-alpine
    container_name: bolna-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - bolna-network

networks:
  bolna-network:
    driver: bridge

volumes:
  redis-data:
    driver: local