services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - APP_TYPE=api
    container_name: bolna-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_TYPE=api
      # Add your API keys here or use a .env file
      # - OPENAI_API_KEY=your_openai_api_key
      # - DEEPGRAM_AUTH_TOKEN=your_deepgram_auth_token
      # - ELEVENLABS_API_KEY=your_elevenlabs_api_key
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - redis
    networks:
      - bolna-network
      
  telephony:
    build:
      context: .
      dockerfile: Dockerfile.telephony
      args:
        - APP_TYPE=telephony
    container_name: bolna-telephony
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_TYPE=telephony
      # Add your telephony API keys here or use a .env file
      # - TWILIO_ACCOUNT_SID=your_twilio_account_sid
      # - TWILIO_AUTH_TOKEN=your_twilio_auth_token
      # - TWILIO_PHONE_NUMBER=your_twilio_phone_number
      # - PLIVO_AUTH_ID=your_plivo_auth_id
      # - PLIVO_AUTH_TOKEN=your_plivo_auth_token
      # - PLIVO_PHONE_NUMBER=your_plivo_phone_number
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - redis
    networks:
      - bolna-network

  redis:
    image: redis:7-alpine
    container_name: bolna-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - bolna-network

networks:
  bolna-network:
    driver: bridge

volumes:
  redis-data:
    driver: local