version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bolna-nest-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Add your API keys here or use a .env file
      # - OPENAI_API_KEY=your_openai_api_key
      # - DEEPGRAM_AUTH_TOKEN=your_deepgram_auth_token
      # - ELEVENLABS_API_KEY=your_elevenlabs_api_key
      # - TWILIO_ACCOUNT_SID=your_twilio_account_sid
      # - TWILIO_AUTH_TOKEN=your_twilio_auth_token
      # - TWILIO_PHONE_NUMBER=your_twilio_phone_number
      # - PLIVO_AUTH_ID=your_plivo_auth_id
      # - PLIVO_AUTH_TOKEN=your_plivo_auth_token
      # - PLIVO_PHONE_NUMBER=your_plivo_phone_number
    volumes:
      - ./.env:/app/.env:ro
      - agent_data:/app/agent_data
    depends_on:
      - redis
    networks:
      - bolna-network

  redis:
    image: redis:7-alpine
    container_name: bolna-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - bolna-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  bolna-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  agent_data:
    driver: local